### ISSUE TITLE
Trying to improve rendering performance

### ISSUE THREAD

**Issue by michaelrambeau** [jvalen/pixel-art-react#9] opened 2016-05-10 21:06 UTC
Using the default grid (20 \* 20 = 400 cells), it seems that there are some rendering performance issues.
For example, if you try to draw a line quickly by drag and drop, some pixels are missing on the screen.
By moving slowly the mouse, it is OK.

![image](https://cloud.githubusercontent.com/assets/5546996/15161638/edb93b9e-1739-11e6-8a52-4568dd46b792.png)

In addition, after having made that line, even if I don't drag any more, pixels are still added on the grid when I simply move the mouse over the grid (I can see in the console that `dragging` flag is still set to `true`).

Note: in production, the performance issues are less obvious than in dev because of several optimizations that make the code run faster. Redux dev tools for example are known to slow down things a lot (a lot of information is logged in the console after every action).
#### Measurements (using React Perf Chrome plugin)

Let's check the rendering process by measuring time before and after rendering a single pixel on the grid.

![image](https://cloud.githubusercontent.com/assets/5546996/15161924/3ee93054-173b-11e6-9d90-9328d10f8e05.png)

`Total time` is not only the same, it is around 500 ms, which is too much time for a single pixel.
I can see that `Connect(PixelCell)` is "wasted" 799 times!

Using a 2 times bigger grid (40 \* 20) `Connect(PixelCell)` is "wasted" 1599 times.

Let's try to fix that!

**Comment by michaelrambeau** [comment] 2016-05-10 21:16
#### Optimization step 1

The Cell component, used to render every pixel on the grid, should be as simple as possible.
Instead of connecting it to the state, let's connect its parent component (the grid) using props to pass actions and context data.

![image](https://cloud.githubusercontent.com/assets/5546996/15162673/2d9c93dc-173f-11e6-873c-4fccf8c89c5f.png)

This is much better, no more 799 occurrences wasted, but it is still slow. We can do better.

**Comment by jvalen** [comment] 2016-05-11 01:33
Thanks a lot @michaelrambeau! **Optimization step 1** is a great performance improvement.

Related to the 3 actions dispatched situation, just to clarify:

1. `SET_GRID_CELL_VALUE`: give a color to the cell clicked.
2. `START_DRAG`: Once we click, we start dragging, meaning that until we release the button we keep giving colors to the cells we move the cursor over.
3. `END_DRAG`: Dispatched when we release the button after dragging.

I should review this mechanism, because looks kind of hacky...
The problem is in the `handleDrag` method, inside PixelCell. You can see the related commit here: 
https://github.com/jvalen/pixel-art-react/commit/0404f01eedbbee1d232e73985270edf0e7e4d825#diff-fcf8f1d2ccbb63938fdda8e82c871866

The reason why I did that is related to **undo history** topic.

The original way of doing that was the following:

```javascript
handleDrag(event) {    
    if (this.props.dragging) {   
      this.drawCell(event);   
    }
  }
```
The problem with the code above was that because we are only storing the following actions dispatched:

```javascript
const store = createStore(undoable(reducer, {
  filter: includeAction([
    'SET_STATE',
    'SET_GRID_DIMENSION',
    'SET_GRID_CELL_VALUE',
    'SET_DRAWING',
    'SET_CELL_SIZE',
    'SET_RESET_GRID'
  ]),
  debug: false
}));
```
When we go back, we remove the last pixel draw but the state contains the **dragging** property to `true` so it keep dragging.

The current way of solving that issue is:
```javascript
handleDrag(event) {
    if (this.props.dragging) {
      this.props.endDrag();
      this.drawCell(event);
      this.props.startDrag();
    }
  }
```
Which thanks to you I realized is not good for performance and we should find a better way of doing that. I don't like having the **dragging** attribute inside the state, it might be the root of the evil.

If you have any suggestions please let me know.

Thanks again!

**Comment by michaelrambeau** [comment] 2016-05-11 20:56
Thank you @jvalen for the explanation. I will go back to the drag and drop stuff later, for now I am doing optimizations that are easy to implement.

### Optimization step 2: make the cell mark-up minimum

In the previous version, every grid cell require 2 `<div>`.

![image](https://cloud.githubusercontent.com/assets/5546996/15195744/23e5a142-1804-11e6-95f4-6077a91aa788.png)

We can make the mark-up simpler, using only one div per cell... and "save" the creation of 400 DOM elements (you cannot imagine the amount of things that the browser creates for a simple `<div>`) !

![image](https://cloud.githubusercontent.com/assets/5546996/15195841/a4fee540-1804-11e6-8102-35f85f9fd733.png)

I used CSS flexbox to get that result.

```css
.grid-container{
  display: flex;
  flex-wrap: wrap;
}
.grid-container .grid-cell{
  border: 1px solid #585858;
  border-width: 0 1px 1px 0;
  color: white;
}
```

Inline style applied on every cell:

```js
const styles = {
    flex: `0 0 ${width}%`,
    paddingBottom: `${width}%`,
    backgroundColor: `#${selectedColor}`
};
```


Impact on performance: it seems the grid render 2 times faster than before (95 ms instead of 185 ms for `Connect(Grid)` )

![image](https://cloud.githubusercontent.com/assets/5546996/15195789/5f21c614-1804-11e6-92bb-c8d8041b73b3.png)

Sounds good but we still can do better!

**Comment by jvalen** [comment] 2016-05-12 00:19
That is also a great improvement, thank you @michaelrambeau.

**Comment by michaelrambeau** [comment] 2016-05-12 21:00
Optimization step 3

* Avoid unnecessary grid rendering, using `shouldComponentUpdate` 
* Move event mouse handler from the `<Cell>` to the `<Grid>` component

```js
  shouldComponentUpdate(nextProps) {
    const same = (key) => { return nextProps[key].equals(this.props[key]); };
    if (same('grid')) {
      // console.info('No need to render the grid!');
      return false;
    }
    return true;
  }
```

it works: when a single pixel is clicked, the grid is rendered only once. Grid component disappeared from the "wasted time"  list.

![image](https://cloud.githubusercontent.com/assets/5546996/15229110/861158ea-18ca-11e6-93e3-606d23cd6b96.png)

We still have work to do because drawing a line is not smooth yet, we should try to empty the list of "wasted" components. Every time a single pixel is clicked, the whole application is rendered, I am going to check if we can optimize this behavior.

**Comment by michaelrambeau** [comment] 2016-05-12 22:26
### Tracking reducer performance

An other idea: checking if reducers are fast using a tool like 'redux-perf-middleware' to see how much time it takes to update the state.

![image](https://cloud.githubusercontent.com/assets/5546996/15232265/16d74d98-18db-11e6-93f3-fbe7eeda2a3e.png)

For a single click that generated 3 actions the reducer was updated in 30ms!
That is pretty slow for pure JavaScript functions; we cannot expect the app to run in 60 FPS ( = 16 ms per frame! )

**Comment by jvalen** [comment] 2016-05-15 16:22
Thank you @michaelrambeau, your performance improvements are merged and up in production.

I'm going to keep this issue opened at least until the **drag** and **drop** topic is solved :smile: .

**Comment by Mayurkoli** [comment] 2018-05-31 11:04
How i learn this

**Comment by jvalen** [comment] 2021-07-16 16:05
I'm closing this issue since it's been a long time with no activity. We might reopen it in the future to talk about performance improvements.

Thanks!

**Closed by jvalen** 2021-07-16 16:05 UTC
